-- insercion de datos de la tabla vendedores
Insert into vendedores (id_personal, nombre, apellido) values (2,' María',' Fernandez');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Laura',' Torres');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Javier',' Jimenez');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Patricia',' Flores');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Beatriz',' Herrera');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Cristina',' Molina');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Olga',' Duran');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Iván',' Garrido');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Victoria',' Hidalgo');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Carmen María',' Lara');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Eduardo',' Salas');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Clara',' Salazar');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Óscar',' Sandoval');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Rosa María',' Villegas');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Ángela',' Zelaya');
Insert into vendedores (id_personal, nombre, apellido) values (2,' María Isabel',' Chacon');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Andrea María',' Cortez');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Santiago',' Escobar');
Insert into vendedores (id_personal, nombre, apellido) values (2,' María',' Fernandez');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Laura',' Torres');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Javier',' Jimenez');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Patricia',' Flores');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Beatriz',' Herrera');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Cristina',' Molina');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Olga',' Duran');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Iván',' Garrido');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Victoria',' Hidalgo');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Carmen María',' Lara');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Eduardo',' Salas');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Clara',' Salazar');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Óscar',' Sandoval');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Rosa María',' Villegas');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Ángela',' Zelaya');
Insert into vendedores (id_personal, nombre, apellido) values (2,' María Isabel',' Chacon');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Andrea María',' Cortez');
Insert into vendedores (id_personal, nombre, apellido) values (2,' Santiago',' Escobar');